############################################################################################
#      NSIS Installation Script created by NSIS Quick Setup Script Generator v1.09.18
#               Entirely Edited with NullSoft Scriptable Installation System                
#              by Vlasis K. Barkas aka Red Wine red_wine@freemail.gr Sep 2006               
############################################################################################

!define APP_NAME "Amazeing Ball"
!define COMP_NAME "Flying Map Entertainment"
!define VERSION "01.00.00.00"
!define COPYRIGHT "Copyright (c) 2025-2026 Flying Map Entertainment"
!define DESCRIPTION "A simple strategy game where the player guides a ball through a rotatable maze."
!define LICENSE_TXT "..\..\LICENSE"
!define INSTALLER_NAME "..\..\abl_dist\Install_Amazeing_Ball_1.0.exe"
!define MAIN_APP_EXE "Amazeing Ball.exe"
!define INSTALL_TYPE "SetShellVarContext all"
!define REG_ROOT "HKLM"
!define REG_APP_PATH "Software\Microsoft\Windows\CurrentVersion\App Paths\${MAIN_APP_EXE}"
!define UNINSTALL_PATH "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"


!define MUI_WELCOMEFINISHPAGE_BITMAP ".\gameplay.bmp"
!define MUI_ICON ".\install_windows.ico"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP ".\header.bmp"

######################################################################

VIProductVersion  "${VERSION}"
VIAddVersionKey "ProductName"  "${APP_NAME}"
VIAddVersionKey "CompanyName"  "${COMP_NAME}"
VIAddVersionKey "LegalCopyright"  "${COPYRIGHT}"
VIAddVersionKey "FileDescription"  "${DESCRIPTION}"
VIAddVersionKey "FileVersion"  "${VERSION}"

######################################################################

SetCompressor ZLIB
Name "${APP_NAME}"
Caption "${APP_NAME}"
OutFile "${INSTALLER_NAME}"
BrandingText "${APP_NAME}"
XPStyle on
InstallDirRegKey "${REG_ROOT}" "${REG_APP_PATH}" ""
InstallDir "$PROGRAMFILES\Flying Map Entertainment\Amazeing Ball"

######################################################################

!include "MUI.nsh"

!define MUI_ABORTWARNING
!define MUI_UNABORTWARNING

!insertmacro MUI_PAGE_WELCOME

!ifdef LICENSE_TXT
!insertmacro MUI_PAGE_LICENSE "${LICENSE_TXT}"
!endif

!insertmacro MUI_PAGE_DIRECTORY

!ifdef REG_START_MENU
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "Flying Map Entertainment"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${REG_ROOT}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${UNINSTALL_PATH}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${REG_START_MENU}"
!insertmacro MUI_PAGE_STARTMENU Application $SM_Folder
!endif

!insertmacro MUI_PAGE_INSTFILES

!define MUI_FINISHPAGE_RUN "$INSTDIR\${MAIN_APP_EXE}"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM

!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_UNPAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

######################################################################

Section -MainProgram
${INSTALL_TYPE}
SetOverwrite ifnewer
SetOutPath "$INSTDIR"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball.exe"
File "..\..\abl_dist\Amazeing Ball\UnityCrashHandler64.exe"
File "..\..\abl_dist\Amazeing Ball\UnityPlayer.dll"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\browscap.ini"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\config"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\mconfig"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\mconfig\config.xml"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\4.5"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.5\DefaultWsdlHelpGenerator.aspx"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.5\machine.config"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.5\settings.map"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.5\web.config"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\Browsers"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.5\Browsers\Compat.browser"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\4.0"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.0\DefaultWsdlHelpGenerator.aspx"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.0\machine.config"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.0\settings.map"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.0\web.config"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\Browsers"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\4.0\Browsers\Compat.browser"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\2.0"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\2.0\DefaultWsdlHelpGenerator.aspx"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\2.0\machine.config"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\2.0\settings.map"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\2.0\web.config"
SetOutPath "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\Browsers"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\etc\mono\2.0\Browsers\Compat.browser"
SetOutPath "$INSTDIR\MonoBleedingEdge\EmbedRuntime"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll"
File "..\..\abl_dist\Amazeing Ball\MonoBleedingEdge\EmbedRuntime\MonoPosixHelper.dll"
SetOutPath "$INSTDIR\D3D12"
File "..\..\abl_dist\Amazeing Ball\D3D12\D3D12Core.dll"
SetOutPath "$INSTDIR\Amazeing Ball_Data"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\app.info"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\boot.config"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\globalgamemanagers"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\globalgamemanagers.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\globalgamemanagers.assets.resS"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level0"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level1"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level10"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level11"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level12"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level13"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level14"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level15"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level16"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level2"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level3"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level4"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level5"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level6"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level7"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level8"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\level9"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\resources.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\resources.assets.resS"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\RuntimeInitializeOnLoads.json"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\ScriptingAssemblies.json"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets0.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets0.assets.resS"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets0.resource"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets1.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets1.assets.resS"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets1.resource"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets10.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets11.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets12.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets13.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets14.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets15.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets16.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets2.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets2.assets.resS"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets2.resource"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets3.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets4.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets5.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets6.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets7.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets8.assets"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\sharedassets9.assets"
SetOutPath "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\catalog.bin"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\catalog.hash"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\settings.json"
SetOutPath "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\8053e85dfc92b6861fab4779b6234753_monoscripts_5faaf9e88a6eae332960b9615adcfa5e.bundle"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\localization-assets-shared_assets_all.bundle"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\localization-locales_assets_all.bundle"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\localization-string-tables-english(en)_assets_all.bundle"
SetOutPath "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\AddressablesLink"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\StreamingAssets\aa\AddressablesLink\link.xml"
SetOutPath "$INSTDIR\Amazeing Ball_Data\Resources"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Resources\unity default resources"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Resources\unity_builtin_extra"
SetOutPath "$INSTDIR\Amazeing Ball_Data\Plugins\x86_64"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Plugins\x86_64\lib_burst_generated.dll"
SetOutPath "$INSTDIR\Amazeing Ball_Data\Managed"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Assembly-CSharp.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Mono.Security.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\mscorlib.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\netstandard.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Newtonsoft.Json.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.ComponentModel.Composition.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Configuration.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Core.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Data.DataSetExtensions.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Data.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Drawing.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.EnterpriseServices.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.IO.Compression.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.IO.Compression.FileSystem.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.IO.Hashing.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Memory.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Net.Http.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Numerics.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Runtime.CompilerServices.Unsafe.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Runtime.Serialization.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Security.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.ServiceModel.Internals.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Transactions.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Xml.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\System.Xml.Linq.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.2D.Animation.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.2D.Common.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.2D.IK.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.2D.PixelPerfect.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.2D.SpriteShape.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.2D.Tilemap.Extras.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Addressables.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Burst.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Burst.Unsafe.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Collections.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Collections.LowLevel.ILSupport.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.InternalAPIEngineBridge.001.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.InternalAPIEngineBridge.013.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Localization.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Mathematics.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Multiplayer.Center.Common.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Profiling.Core.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Rendering.LightTransport.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipeline.Universal.ShaderLibrary.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Core.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Core.Runtime.Shared.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Core.ShaderLibrary.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.GPUDriven.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.2D.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.Config.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.Shaders.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.ResourceManager.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.ScriptableBuildPipeline.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.TextMeshPro.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.Timeline.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.VisualScripting.Antlr3.Runtime.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.VisualScripting.Core.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.VisualScripting.DocCodeExamples.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.VisualScripting.Flow.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\Unity.VisualScripting.State.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AccessibilityModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AIModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AMDModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AndroidJNIModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AnimationModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ARModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AssetBundleModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.AudioModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ClothModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ClusterInputModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ClusterRendererModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ContentLoadModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.CoreModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.CrashReportingModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.DirectorModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.DSPGraphModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.GameCenterModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.GIModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.GraphicsStateCollectionSerializerModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.GridModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.HierarchyCoreModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.HotReloadModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.IdentifiersModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ImageConversionModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.IMGUIModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.InputForUIModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.InputLegacyModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.InputModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.InsightsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.JSONSerializeModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.LocalizationModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.MarshallingModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.MultiplayerModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.NVIDIAModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ParticleSystemModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.PerformanceReportingModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.Physics2DModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.PhysicsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.PropertiesModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ScreenCaptureModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.ShaderVariantAnalyticsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.SharedInternalsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.SpriteMaskModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.SpriteShapeModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.StreamingModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.SubstanceModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.SubsystemsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TerrainModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TerrainPhysicsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TextRenderingModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TilemapModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.TLSModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UI.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UIElementsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UIModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UmbraModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityAnalyticsModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityConnectModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityConsentModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityCurlModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityTestProtocolModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.VehiclesModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.VFXModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.VideoModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.VirtualTexturingModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.VRModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.WindModule.dll"
File "..\..\abl_dist\Amazeing Ball\Amazeing Ball_Data\Managed\UnityEngine.XRModule.dll"
SectionEnd

######################################################################

Section -Icons_Reg
SetOutPath "$INSTDIR"
WriteUninstaller "$INSTDIR\uninstall.exe"

!ifdef REG_START_MENU
!insertmacro MUI_STARTMENU_WRITE_BEGIN Application
CreateDirectory "$SMPROGRAMS\$SM_Folder"
CreateShortCut "$SMPROGRAMS\$SM_Folder\${APP_NAME}.lnk" "$INSTDIR\${MAIN_APP_EXE}"
CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${MAIN_APP_EXE}"
CreateShortCut "$SMPROGRAMS\$SM_Folder\Uninstall ${APP_NAME}.lnk" "$INSTDIR\uninstall.exe"

!ifdef WEB_SITE
WriteIniStr "$INSTDIR\${APP_NAME} website.url" "InternetShortcut" "URL" "${WEB_SITE}"
CreateShortCut "$SMPROGRAMS\$SM_Folder\${APP_NAME} Website.lnk" "$INSTDIR\${APP_NAME} website.url"
!endif
!insertmacro MUI_STARTMENU_WRITE_END
!endif

!ifndef REG_START_MENU
CreateDirectory "$SMPROGRAMS\Flying Map Entertainment"
CreateShortCut "$SMPROGRAMS\Flying Map Entertainment\${APP_NAME}.lnk" "$INSTDIR\${MAIN_APP_EXE}"
CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${MAIN_APP_EXE}"
CreateShortCut "$SMPROGRAMS\Flying Map Entertainment\Uninstall ${APP_NAME}.lnk" "$INSTDIR\uninstall.exe"

!ifdef WEB_SITE
WriteIniStr "$INSTDIR\${APP_NAME} website.url" "InternetShortcut" "URL" "${WEB_SITE}"
CreateShortCut "$SMPROGRAMS\Flying Map Entertainment\${APP_NAME} Website.lnk" "$INSTDIR\${APP_NAME} website.url"
!endif
!endif

WriteRegStr ${REG_ROOT} "${REG_APP_PATH}" "" "$INSTDIR\${MAIN_APP_EXE}"
WriteRegStr ${REG_ROOT} "${UNINSTALL_PATH}"  "DisplayName" "${APP_NAME}"
WriteRegStr ${REG_ROOT} "${UNINSTALL_PATH}"  "UninstallString" "$INSTDIR\uninstall.exe"
WriteRegStr ${REG_ROOT} "${UNINSTALL_PATH}"  "DisplayIcon" "$INSTDIR\${MAIN_APP_EXE}"
WriteRegStr ${REG_ROOT} "${UNINSTALL_PATH}"  "DisplayVersion" "${VERSION}"
WriteRegStr ${REG_ROOT} "${UNINSTALL_PATH}"  "Publisher" "${COMP_NAME}"

!ifdef WEB_SITE
WriteRegStr ${REG_ROOT} "${UNINSTALL_PATH}"  "URLInfoAbout" "${WEB_SITE}"
!endif
SectionEnd

######################################################################

Section Uninstall
${INSTALL_TYPE}
Delete "$INSTDIR\Amazeing Ball.exe"
Delete "$INSTDIR\UnityCrashHandler64.exe"
Delete "$INSTDIR\UnityPlayer.dll"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\browscap.ini"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\mconfig\config.xml"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\DefaultWsdlHelpGenerator.aspx"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\machine.config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\settings.map"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\web.config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\Browsers\Compat.browser"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\DefaultWsdlHelpGenerator.aspx"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\machine.config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\settings.map"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\web.config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\Browsers\Compat.browser"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\DefaultWsdlHelpGenerator.aspx"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\machine.config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\settings.map"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\web.config"
Delete "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\Browsers\Compat.browser"
Delete "$INSTDIR\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll"
Delete "$INSTDIR\MonoBleedingEdge\EmbedRuntime\MonoPosixHelper.dll"
Delete "$INSTDIR\D3D12\D3D12Core.dll"
Delete "$INSTDIR\Amazeing Ball_Data\app.info"
Delete "$INSTDIR\Amazeing Ball_Data\boot.config"
Delete "$INSTDIR\Amazeing Ball_Data\globalgamemanagers"
Delete "$INSTDIR\Amazeing Ball_Data\globalgamemanagers.assets"
Delete "$INSTDIR\Amazeing Ball_Data\globalgamemanagers.assets.resS"
Delete "$INSTDIR\Amazeing Ball_Data\level0"
Delete "$INSTDIR\Amazeing Ball_Data\level1"
Delete "$INSTDIR\Amazeing Ball_Data\level10"
Delete "$INSTDIR\Amazeing Ball_Data\level11"
Delete "$INSTDIR\Amazeing Ball_Data\level12"
Delete "$INSTDIR\Amazeing Ball_Data\level13"
Delete "$INSTDIR\Amazeing Ball_Data\level14"
Delete "$INSTDIR\Amazeing Ball_Data\level15"
Delete "$INSTDIR\Amazeing Ball_Data\level16"
Delete "$INSTDIR\Amazeing Ball_Data\level2"
Delete "$INSTDIR\Amazeing Ball_Data\level3"
Delete "$INSTDIR\Amazeing Ball_Data\level4"
Delete "$INSTDIR\Amazeing Ball_Data\level5"
Delete "$INSTDIR\Amazeing Ball_Data\level6"
Delete "$INSTDIR\Amazeing Ball_Data\level7"
Delete "$INSTDIR\Amazeing Ball_Data\level8"
Delete "$INSTDIR\Amazeing Ball_Data\level9"
Delete "$INSTDIR\Amazeing Ball_Data\resources.assets"
Delete "$INSTDIR\Amazeing Ball_Data\resources.assets.resS"
Delete "$INSTDIR\Amazeing Ball_Data\RuntimeInitializeOnLoads.json"
Delete "$INSTDIR\Amazeing Ball_Data\ScriptingAssemblies.json"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets0.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets0.assets.resS"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets0.resource"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets1.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets1.assets.resS"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets1.resource"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets10.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets11.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets12.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets13.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets14.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets15.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets16.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets2.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets2.assets.resS"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets2.resource"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets3.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets4.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets5.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets6.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets7.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets8.assets"
Delete "$INSTDIR\Amazeing Ball_Data\sharedassets9.assets"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\catalog.bin"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\catalog.hash"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\settings.json"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\8053e85dfc92b6861fab4779b6234753_monoscripts_5faaf9e88a6eae332960b9615adcfa5e.bundle"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\localization-assets-shared_assets_all.bundle"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\localization-locales_assets_all.bundle"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64\localization-string-tables-english(en)_assets_all.bundle"
Delete "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\AddressablesLink\link.xml"
Delete "$INSTDIR\Amazeing Ball_Data\Resources\unity default resources"
Delete "$INSTDIR\Amazeing Ball_Data\Resources\unity_builtin_extra"
Delete "$INSTDIR\Amazeing Ball_Data\Plugins\x86_64\lib_burst_generated.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Assembly-CSharp.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Mono.Security.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\mscorlib.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\netstandard.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Newtonsoft.Json.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.ComponentModel.Composition.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Configuration.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Core.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Data.DataSetExtensions.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Data.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Drawing.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.EnterpriseServices.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.IO.Compression.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.IO.Compression.FileSystem.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.IO.Hashing.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Memory.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Net.Http.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Numerics.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Runtime.CompilerServices.Unsafe.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Runtime.Serialization.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Security.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.ServiceModel.Internals.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Transactions.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Xml.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\System.Xml.Linq.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.2D.Animation.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.2D.Common.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.2D.IK.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.2D.PixelPerfect.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.2D.SpriteShape.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.2D.Tilemap.Extras.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Addressables.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Burst.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Burst.Unsafe.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Collections.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Collections.LowLevel.ILSupport.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.InternalAPIEngineBridge.001.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.InternalAPIEngineBridge.013.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Localization.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Mathematics.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Multiplayer.Center.Common.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Profiling.Core.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Rendering.LightTransport.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipeline.Universal.ShaderLibrary.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Core.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Core.Runtime.Shared.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Core.ShaderLibrary.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.GPUDriven.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.2D.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.Config.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.RenderPipelines.Universal.Shaders.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.ResourceManager.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.ScriptableBuildPipeline.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.TextMeshPro.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.Timeline.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.VisualScripting.Antlr3.Runtime.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.VisualScripting.Core.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.VisualScripting.DocCodeExamples.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.VisualScripting.Flow.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\Unity.VisualScripting.State.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AccessibilityModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AIModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AMDModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AndroidJNIModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AnimationModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ARModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AssetBundleModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.AudioModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ClothModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ClusterInputModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ClusterRendererModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ContentLoadModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.CoreModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.CrashReportingModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.DirectorModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.DSPGraphModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.GameCenterModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.GIModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.GraphicsStateCollectionSerializerModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.GridModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.HierarchyCoreModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.HotReloadModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.IdentifiersModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ImageConversionModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.IMGUIModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.InputForUIModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.InputLegacyModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.InputModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.InsightsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.JSONSerializeModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.LocalizationModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.MarshallingModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.MultiplayerModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.NVIDIAModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ParticleSystemModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.PerformanceReportingModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.Physics2DModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.PhysicsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.PropertiesModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ScreenCaptureModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.ShaderVariantAnalyticsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.SharedInternalsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.SpriteMaskModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.SpriteShapeModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.StreamingModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.SubstanceModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.SubsystemsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TerrainModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TerrainPhysicsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TextRenderingModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TilemapModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.TLSModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UI.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UIElementsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UIModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UmbraModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityAnalyticsModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityConnectModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityConsentModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityCurlModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityTestProtocolModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.VehiclesModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.VFXModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.VideoModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.VirtualTexturingModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.VRModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.WindModule.dll"
Delete "$INSTDIR\Amazeing Ball_Data\Managed\UnityEngine.XRModule.dll"
 
RmDir "$INSTDIR\Amazeing Ball_Data\Managed"
RmDir "$INSTDIR\Amazeing Ball_Data\Plugins\x86_64"
RmDir "$INSTDIR\Amazeing Ball_Data\Resources"
RmDir "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\AddressablesLink"
RmDir "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa\StandaloneWindows64"
RmDir "$INSTDIR\Amazeing Ball_Data\StreamingAssets\aa"
RmDir "$INSTDIR\Amazeing Ball_Data"
RmDir "$INSTDIR\D3D12"
RmDir "$INSTDIR\MonoBleedingEdge\EmbedRuntime"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\2.0\Browsers"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\2.0"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\4.0\Browsers"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\4.0"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\4.5\Browsers"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\4.5"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono\mconfig"
RmDir "$INSTDIR\MonoBleedingEdge\etc\mono"
 
Delete "$INSTDIR\uninstall.exe"
!ifdef WEB_SITE
Delete "$INSTDIR\${APP_NAME} website.url"
!endif

RmDir "$INSTDIR"

!ifdef REG_START_MENU
!insertmacro MUI_STARTMENU_GETFOLDER "Application" $SM_Folder
Delete "$SMPROGRAMS\$SM_Folder\${APP_NAME}.lnk"
Delete "$SMPROGRAMS\$SM_Folder\Uninstall ${APP_NAME}.lnk"
!ifdef WEB_SITE
Delete "$SMPROGRAMS\$SM_Folder\${APP_NAME} Website.lnk"
!endif
Delete "$DESKTOP\${APP_NAME}.lnk"

RmDir "$SMPROGRAMS\$SM_Folder"
!endif

!ifndef REG_START_MENU
Delete "$SMPROGRAMS\Flying Map Entertainment\${APP_NAME}.lnk"
Delete "$SMPROGRAMS\Flying Map Entertainment\Uninstall ${APP_NAME}.lnk"
!ifdef WEB_SITE
Delete "$SMPROGRAMS\Flying Map Entertainment\${APP_NAME} Website.lnk"
!endif
Delete "$DESKTOP\${APP_NAME}.lnk"

RmDir "$SMPROGRAMS\Flying Map Entertainment"
!endif

DeleteRegKey ${REG_ROOT} "${REG_APP_PATH}"
DeleteRegKey ${REG_ROOT} "${UNINSTALL_PATH}"
SectionEnd

######################################################################

